<?php
// $Id$

/**
 * Search service class using Solr server.
 */
class SearchApiSolrService extends SearchApiAbstractService {

  public function configurationForm() {

  }

  public function addIndex(SearchApiIndex $index) {

  }

  public function fieldsUpdated(SearchApiIndex $index) {

  }

  public function removeIndex($index) {

  }

  public function indexItems(SearchApiIndex $index, array $items) {

  }

  public function deleteItems($ids, SearchApiIndex $index = NULL) {

  }

  public function search(SearchApiQueryInterface $query) {

  }

}
